FROM jupyter/minimal-notebook:python-3.8.8
EXPOSE 8888
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=", "--NotebookApp.disable_check_xsrf=True"]
